sassoftware/viya4-iac-gcp

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars

#85 clarify BYO subnet variable syntax

---

modules/network/outputs.tf

#87 align types in network module output

---

docs/CONFIG-VARS.md
docs/user/TerraformGCPAuthentication.md
main.tf
variables.tf

a preparatory step for the Private Cluster work.

allow VM Service Account authentication (#98)

---

docs/CONFIG-VARS.md
main.tf
network.tf
variables.tf

address (JIRA-292) and (JIRA-293)

add postgres and filestore cidr ranges

---

locals.tf
main.tf
variables.tf

This change does introduce a new variable, but intentionally not added to CONFIG-VARS.md.
It's a complex issue. If there is a need for documentation, a might want to have a separate page.

set number of initial nodes to overcome the Ingress quota limit of 100

---

docs/CONFIG-VARS.md
docs/user/APIServices.md
main.tf
outputs.tf
variables.tf

enable and document GCR access

---

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-defaults.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input.tfvars
locals.tf

- require only when jump or nfs vm is being created
- doc: move from Required to General section
- remove from examples

make ssh_public_key optional

---

docs/CONFIG-VARS.md
docs/user/APIServices.md
docs/user/AdvancedTerraformUsage.md
docs/user/DockerUsage.md
docs/user/Kubeconfig.md
docs/user/TerraformGCPAuthentication.md
docs/user/TerraformUsage.md

Includes:
* Misc. documentation fixes & cleanup
* Fixes #112

(IAC-410) Documentation Updates & Cleanup

---

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input.tfvars
locals.tf
main.tf
network.tf
outputs.tf
variables.tf

(IAC-465) Update the default K8s version in the examples tfvars

Monthly Release - 2.3.0

---

Dockerfile

Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/

(IAC-531) Update safe directory in Dockerfile

---

docs/sas-updates.md

New Readme document added for remove connect class.

(IAC-534) New Readme for remove connect class in iac-gcp

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input.tfvars
main.tf
modules/kubeconfig/main.tf
variables.tf
versions.tf

3.2.0 - September 01, 2022

---

README.md
docs/CONFIG-VARS.md
locals.tf
main.tf
modules/google_vm/main.tf
modules/network/variables.tf
network.tf
variables.tf
versions.tf

4.0.0 - October 20, 2022

---

main.tf

bug: (IAC-875) Reverted local from location -> zone

---

Dockerfile
README.md
config/sample-input-tf-enterprise.tfvars
docs/user/KubernetesVersions.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input.tfvars
variables.tf

4.3.0 - March 16, 2023

---

docker-entrypoint.sh
files/tools/iac_git_info.sh
files/tools/iac_tooling_version.sh
locals.tf
main.tf
modules/google_vm/main.tf
modules/google_vm/outputs.tf
modules/google_vm/variables.tf
modules/kubeconfig/locals.tf
modules/kubeconfig/main.tf
modules/kubeconfig/outputs.tf
modules/kubeconfig/variables.tf
modules/network/main.tf
modules/network/outputs.tf
modules/network/variables.tf
network.tf
outputs.tf
variables.tf
versions.tf
vms.tf

Adds copyright information to our source files
Successfully built the docker image and used it to create & destroy infrastructure.

feat: (IAC-936) Add Copyright Information

---

docker-entrypoint.sh
files/tools/iac_git_info.sh
files/tools/iac_tooling_version.sh
locals.tf
main.tf
modules/google_vm/main.tf
modules/google_vm/outputs.tf
modules/google_vm/variables.tf
modules/kubeconfig/locals.tf
modules/kubeconfig/main.tf
modules/kubeconfig/outputs.tf
modules/kubeconfig/variables.tf
modules/network/main.tf
modules/network/outputs.tf
modules/network/variables.tf
network.tf
outputs.tf
variables.tf
versions.tf
vms.tf

4.3.1 - March 28, 2023

---

.pre-commit-config_template.yaml
docs/CONFIG-VARS.md
locals.tf
main.tf
outputs.tf
variables.tf

4.4.0 - April 20, 2023

---

Dockerfile
README.md
config/sample-input-tf-enterprise.tfvars
docs/user/Kubeconfig.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input.tfvars
main.tf
modules/kubeconfig/locals.tf
versions.tf

4.5.0 - May 18, 2023

---

Dockerfile
README.md
main.tf
modules/google_vm/main.tf
network.tf
versions.tf
vms.tf

stagingplus to Staging

---

Dockerfile
README.md
main.tf
modules/google_vm/main.tf
network.tf
versions.tf
vms.tf

5.0.0 - May 25, 2023

---

.github/workflows/linter-analysis.yaml
Dockerfile
docker-entrypoint.sh
linting-configs/.hadolint.yaml
linting-configs/.shellcheckrc
linting-configs/.tflint.hcl
locals.tf
main.tf
modules/google_vm/outputs.tf
modules/google_vm/variables.tf
modules/kubeconfig/locals.tf
modules/network/main.tf
modules/network/outputs.tf
modules/network/variables.tf
network.tf
outputs.tf
variables.tf
vms.tf

5.2.0 - June 26, 2023

---

Dockerfile
docs/CONFIG-VARS.md
docs/user/APIServices.md
docs/user/DockerUsage.md
linting-configs/.hadolint.yaml

5.3.0 - July 20, 2023

---

docs/CONFIG-VARS.md
variables.tf

5.5.0 - September 21, 2023

---

README.md
docs/CONFIG-VARS.md
docs/sas-updates.md

Update the SAS Documentation links to `documentation.sas.com`

docs: (IAC-1085) Update SAS Documentation URLs

---

Dockerfile
README.md
main.tf
modules/google_vm/main.tf
network.tf
variables.tf
versions.tf

5.8.0 - February 15, 2024 

---

Dockerfile
docker-entrypoint.sh
files/tools/iac_git_info.sh
files/tools/iac_tooling_version.sh
locals.tf
main.tf
modules/google_vm/main.tf
modules/google_vm/outputs.tf
modules/google_vm/variables.tf
modules/kubeconfig/locals.tf
modules/kubeconfig/main.tf
modules/kubeconfig/outputs.tf
modules/kubeconfig/variables.tf
modules/network/main.tf
modules/network/outputs.tf
modules/network/variables.tf
network.tf
outputs.tf
variables.tf
versions.tf
vms.tf

Update copyright year
| Scenario | Provider | K8s Version          | Notes         |
|----------|----------|----------------------|---------------|
| 1        | GCP      | v1.27.12-gke.1115000 | apply/destroy |

docs: (IAC-1413) Update Copyright Information

---

Dockerfile
README.md

6.2.0 - May 17, 2024

---

.github/workflows/linter-analysis.yaml
CONTRIBUTING.md
docs/CONFIG-VARS.md
examples/sample-input.tfvars
main.tf
variables.tf

* https://github.com/sassoftware/viya4-iac-gcp/pull/255
* https://github.com/sassoftware/viya4-iac-gcp/pull/253
* https://github.com/sassoftware/viya4-iac-gcp/pull/252
* https://github.com/sassoftware/viya4-iac-gcp/pull/257

7.5.0 - May 8, 2025 

---

examples/sample-input-singlestore.tfvars

feat: (pscloud-92) add support for SAS with SingleStore on GCP
- Enhanced IAC to enable SAS deployments with SingleStore.
- Updated configuration and provisioning scripts.

feat: (pscloud-92) enable SAS with SingleStore on GCP
