sassoftware/viya4-iac-gcp

- modules/google_vm/variables.tf
- vm.tf
Closes #89 - Updating the OS resolves the `googe-guest-agent` package issue.
> Updated Jump/NFS Server OS to 20.04 resolving google-guest-agent issue

- modules/network/outputs.tf
Closes #87 - Output logic now works for both the automatic and byo networking when one applies and destroys their cluster.
> network outputs for auto / byo now fixed

- modules/network/outputs.tf
Closes #93 - Added `try` wrappers on indexed output items that may be empty when a value is required.
> Fixed subnet output issues

- docs/CONFIG-VARS.md
- main.tf
- variables.tf
- use new V1 names (BASIC_HDD, BASIC_SSD)
- support old names (STANDARD, PREMIUM), but do not document
- increase default size to minimum required by BASIC_SSD (2T)
- do not support HIGH_SCALE_SSD since it is still Beta
> Filestore tier/size parameters (#63)

- Dockerfile
- README.md
- examples/sample-input-byo.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
* Default `kubernetes_version` updated to `1.21.6-gke.1500` in example files
* Update Dockerfile to install 1.21.6 `kubectl` binary
* Update README to reflect new `kubectl` version
Test Coverage:
Verified in GCP with default K8s `1.21.6-gke.1500`, viya4 deployment, logging and monitoring were successful.
> (IAC-396) Update viya4-iac-gcp default K8s version to 1.21.x

- Dockerfile
- README.md
Update the default kubectl version in the Dockerfile and the README to 1.21.7
> (IAC-396) Update kubectl to 1.21.7

- main.tf
Migrates to the cos_containerd node pool image so that the nodes will now use the containerd container runtime.
https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd#migrating
This change is also taking place since the Docker container runtime will no longer be supported by Kubernetes in the upcoming v1.24 release.
https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/
Tests:
Was able to create both a v1.22.3-gke.1500  & v1.21.6-gke.1500 with the cos_containerd node pool image and perform a successful Viya/Monitoring/Logging deployment on them.
> (IAC-404) Migrate to the cos_containerd Node Pool Image

- examples/sample-input-byo.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
Update the example versions to 1.21.6-gke.1503, the old version has been removed by Google.
https://cloud.google.com/kubernetes-engine/docs/release-notes-regular#2022-r03_version_updates
Test:
- Was able to create a 1.21.6-gke.1503 cluster with the sample template and perform a successful deployment on it.
> (IAC-465) Update the default K8s version in the examples tfvars

- Dockerfile
Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/
> (IAC-531) added git share directive for viya4-iac-gcp

- Dockerfile
- README.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
Since Viya will be supporting 1.21, 1.22, and 1.23 in June, the kubectl version is being changed to 1.22 so that it's within the +/- 1 range of the supported versions. The default version in the example .tfvars is also being changed to 1.22.9-gke.1500 so that it is also in the middle of the support version range. 
Test summary, more detail is present in the internal ticket.
| Cloud Provider | kubectl version | K8s Version      | Cadence   | Ingress-nginx version | Deployment Stabilized |
|----------------|-----------------|------------------|-----------|-----------------------|-----------------------|
| GCP            | 1.22.10         | 1.22.9-gke.1500  | Fast:2020 | v1.1.1                | Yes                   |
| GCP            | 1.22.10         | 1.22.9-gke.1500  | 2022.1.1  | v1.1.1 …
> (IAC-542) Update kubectl and default K8s version to 1.22

- Dockerfile
- README.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
(IAC-542) Update kubectl and default K8s version to 1.22 [#134](https://github.com/sassoftware/viya4-iac-gcp/pull/134)
> 3.1.0 - June 17, 2022

- Dockerfile
- README.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- main.tf
- modules/kubeconfig/main.tf
- variables.tf
- versions.tf
Starting from Kubernetes version `1.24.0` service account token is not automatically generated, thus it has to be created separately. The following resources were updated by the provider `hashicorp/kubernetes` to handle this change in `v2.13.0`: `d/kubernetes_service_account`, `r/kubernetes_default_service_account`, `r/kubernetes_service_account`. For Kubernetes clusters running v1.24+ `default_secret_name` will be empty. A warning message will be printed once any of the above resources are in use. 
* To support 1.24+ Kubernetes version in GKE, a secret is manually created for the service account
* The default K8s value is updated from 1.22.9-gke.1500 to 1.23.8-gke.1900
* The default kubectl value is updated from 1.22.10 to 1.23.8
* The …
> feat: (IAC-654) GKE add support for K8s 1.24

- docs/CONFIG-VARS.md
Update the default value for `create_static_kubeconfig` in the docs/CONFIG-VARS.md documentation.
> docs: (IAC-654) Update default value for create_static_kubeconfig

- docs/CONFIG-VARS.md
- variables.tf
Changes the default value for  the `server_version` variable which is contained within the `postgres_server_defaults` map to 13.
The user can select any version between 11-14 to suite their SAS Viya deployment requirements.
Ran through the following deployment scenarios to test out PG
| Scenario | Provider | K8s Version | PG Version | Order | Cadence | Deployment Stabilized | Notes |
|---|---|---|---|---|---|---|---|
| PostgreSQL V11 | GCP | v1.23.8-gke.1900 | 11.16 | * | Fast:2020 | Yes |  |
| PostgreSQL V12 | GCP | v1.23.8-gke.1900 | 12.11 | * | Fast:2020 | Yes |  |
| PostgreSQL V13 | GCP | v1.23.8-gke.1900 | 13.7 | *| Fast:2020 | Yes | New default, did not define server_version in .tfvars |
| PostgreSQL V14 | GCP | v1.23.8-gke.1900 | 14.4 | *| Fast:2020 | Yes |  |
> feat: (IAC-705) Update default PostgreSQL server_version to 13

- README.md
- locals.tf
- main.tf
- modules/google_vm/main.tf
- modules/network/variables.tf
- network.tf
- variables.tf
- versions.tf
* hashicorp/google & hashicorp/google-beta
- 3.78.0 -> 4.38.0
- Change Log v3: https://github.com/hashicorp/terraform-provider-google/blob/v3.90.1/CHANGELOG.md
- Upgrade Guide v4: https://github.com/hashicorp/terraform-provider-google/blob/main/website/docs/guides/version_4_upgrade.html.markdown
- Change Log v4: https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md
* hashicorp/external
-  2.1.0 -> 2.2.2
- Change Log: https://github.com/hashicorp/terraform-provider-external/blob/main/CHANGELOG.md
*  hashicorp/local
- 2.1.0 -> 2.2.3
- Change Log: https://github.com/hashicorp/terraform-provider-local/blob/main/CHANGELOG.md
* module.postgresql
- Source: GoogleCloudPlatform/sql-db/google//modules/postgresql
- 6.0.0 -> 12.0.0
- Change Log: …
> feat: (IAC-476) Update Providers, Modules, & Dependencies

- main.tf
The `google_filestore_instance` resource `location` parameter needs to be a zone value
See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/filestore_instance
In my tfvars I set my location to "location", the code locals.tf successfully selected the first zone from that location and local.zone was successfully used for the filestore resource.
> fix: (IAC-476) Change Filestore location param value

- locals.tf
- main.tf
Made a change so that the default `max_prepared_transactions` & `max_connections` is set to 1024 for each Postgres server as recommended by the Viya deployment guide. The user is still able to override these values themselves with the existing `database_flags` parameter. 
Ran through the following scenarios.
See internal ticket for artifacts/additional details
1. Check default settings are applied `[{ name = "max_prepared_transactions", value = "1024" }, { name = "max_connections", value = "1024" }]` and Viya was successfully deployed
2. Verified the user can override the `database_flags` with their own values and it correct merges with the `base_database_flags`
3. Update `max_connections` in .tfvars and reapply, GCP automatically restarts the DB server and the new value is applied …
> feat: (IAC-193) Add base max_connections and max_prepared_transactions values

- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
Update `kubernetes_version` to `1.23.14-gke.401` in the example .tfvars
Earlier this week `1.23.8-gke.1900` the default GCP K8s version that we have in the example file has been removed
Release Notes: https://cloud.google.com/kubernetes-engine/docs/release-notes#December_05_2022
See internal ticket 
|Scenario|Deployment Method|Security|K8s Version|Orchestration|Provider|Cadence|Postgres|V4_DEPLOYMENT_OPERATOR_ENABLED|
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|1|docker|front-door|1.23.14-gke.401|Deploy|GCP|fast:2020|internal|FALSE||
> feat: (IAC-822) Update kubernetes_version to 1.23.14-gke.401 in tfvars

- README.md
- docs/CONFIG-VARS.md
- docs/sas-updates.md
Updating the SAS Viya name in the documentation
The repo's "About" section will also need to change as part of this PR, since that's not controlled by the code I'll put the updated content here. Please review this as well.
>This project contains Terraform configuration files to provision infrastructure components required to deploy SAS Viya platform products on Google GCP.
> docs: (IAC-864) Update SAS Viya name in documentation

- Dockerfile
- README.md
- config/sample-input-tf-enterprise.tfvars
- docs/user/KubernetesVersions.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- variables.tf
Since the SAS Viya Platform will be supporting K8s 1.23, 1.24, and 1.25 in March as part of the 2023.03 cadence, the kubectl version is being changed to 1.24.10 so that it's within the +/- 1 range of the supported versions. 
We've also now added support for using aliased kubernetes versions.
This is only applicable in the "version based" scenario (omitting `kubernetes_channel` or setting it to "UNSPECIFIED"), Google supports the use of [aliased versions](https://cloud.google.com/kubernetes-engine/versioning#specifying_cluster_version) when creating your kubernetes cluster. The required format for using aliased versions in your tfvars for `kubernetes_version` looks like:
* 1.X
* Specifies the highest valid patch+gke.N patch release in the 1.X minor version
* 1.X.Y
* Specifies the highest …
> feat: (IAC-901) Add K8s 1.25 support and Support Aliased Versions

- .pre-commit-config_template.yaml
Add pre-commit tool .pre-commit-config_template.yaml configuration template file.
Additional steps are required to begin using the pre-commit tool with template file content.
See internal ticket description for steps on how to get started using the pre-commit tool.
> feat: (IAC-442) Add pre-commit tool config.yaml template

- docs/CONFIG-VARS.md
- locals.tf
- main.tf
- outputs.tf
- variables.tf
Added new variables to allow the user to control the location of the default node pool as well as any additional node pools in order to support  multi-zonal clusters.
The user can set `nodepools_locations` and `default_nodepool_locations` to a comma separated list of zones where the node pools will allocate nodes into. It's important that these `nodepools_locations` and `default_nodepool_locations` variables only have zones defined that are within the location your specified for the control plane. If `location` for the control plane is set to us-east1 you can only use set the `nodepools_locations` and `default_nodepool_locations` zones to be us-east1-* and not zones from other regions.
if these variables are not set its default value will be the single zone, the first zone found for the …
> feat: (IAC-74) Support Multi-zonal Cluster Creation

- main.tf
When the user sets `UNSPECIFIED` for the `kubernetes_channel` do not set `release_channel` to null and rely on the default value downstream. Instead we will be explicitly setting  `release_channel` it to the value  in  `kubernetes_channel`.
We are doing this because apparently there was a underlying GKE API change where setting the `release_channel` to null would now default to the `REGULAR` channel. It was advised to no longer set this value to null. See this GitHub issue I opened against the `terraform-google-modules/kubernetes-engine` module
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1620
They are working on getting the doc updated in the next module release.
Note:
* `kubernetes_channel`: the variable we expose to users in this project to …
> fix: (IAC-1008) Explicitly Set the release_channel when Creating GKE Clusters

- Dockerfile
- README.md
- versions.tf
Updated the default and minimum required Terraform version to 1.4.5, to pull in the latest features, fixes, and security patches from HashiCorp.
Consumers of the Dockerfile will already have the version updated within the installation stages. For users that are running viya4-iac-gcp directly on their machine without the use of the Docker container (by executing the `terraform` command) should update their Terraform version to at least 1.4.5.
**Note** This is the new PR after the revert from earlier.
| Scenario | Provider | kubernetes_version      | kubectl version | Deployment Method | Terraform Version | Order  | Cadence   | Notes                               |
| -------- | -------- | ----------------------- | --------------- | ----------------- | ----------------- | ------ | --------- …
> feat!: (IAC-970) Update Terraform Version to 1.4.5

- main.tf
- modules/google_vm/main.tf
- network.tf
- versions.tf
- vms.tf
Update the viya4-iac-gcp Providers, Modules, & Dependencies and Patch Security Issues
Below is notes and changes that I made as I upgraded the modules/providers.
* Versions:
* Initial Version: 4.38.0
* Final Version: 4.63.1
* Notes:
* No notable breaking changes or deprecations observed that would affect us, mostly the addition of new features.
* Change Log: https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md
* Versions:
* Initial Version: 2.14.0
* Final Version: 2.20.0
* Notes:
* No notable breaking changes or deprecations observed that would affect us, mostly the addition of new resources.
* Change Log: https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md
* Versions:
* Initial Version: 2.2.3
* Final Version: 2.4.0
* Notes:
* No …
> feat!: (IAC-997) (IAC-995) Update viya4-iac-gcp Providers, Modules, & Dependencies and Patch Security Issues

- docs/CONFIG-VARS.md
- main.tf
- variables.tf
After March 15, 2023 all newly created Google Kubernetes Engine standard clusters will have [Managed Service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus) in-cluster components deployed by default.
This default enabled feature from Google does add a small amount of cost. See https://cloud.google.com/stackdriver/pricing#mgd-prometheus-pricing-summary
In order to support users who do want this service in their cluster by default we are adding the `enable_managed_prometheus` to control the deployment of the  "Managed Service for Prometheus" in their clusters. By default we are setting this value to false.
Note: Google has still not enabled this feature by default, but adding the flag as a feature in case users want to enable this themselves.
| Scenario | …
> feat: (IAC-895) Add Support to Toggle the Google Cloud Managed Service for Prometheus

- Dockerfile
- docs/CONFIG-VARS.md
- main.tf
- variables.tf
> 5.1.0 - June 15, 2023

- docs/CONFIG-VARS.md
- variables.tf
Update the documentation for the `enable_cluster_autoscaling` variable to make it more clear to the user what it does.
The scaling of nodes within node pools (e.g. additional stateful or cas nodes) is what someone typically thinks of when reading the word autoscaling and the limits are controlled by the existing `min_nodes` & `max_nodes` variables when configuring the node_pool map within your terraform.tfvars See: https://github.com/sassoftware/viya4-iac-gcp/blob/main/docs/CONFIG-VARS.md#additional-nodepools
The `enable_cluster_autoscaling` variable configures the creation of additional **new** node pools when resources requests are made and no existing node pools or nodes can satisfy the request. In our Terraform code the variable is exposed to the user as `enable_cluster_autoscaling` …
> docs: (IAC-977) Update enable_cluster_autoscaling documentation

- Dockerfile
- README.md
Updates the Google Cloud CLI to 440.0.0 to pick up the latest updates
In viya4-iac-gcp since the CLI is delivered via the `google/cloud-sdk:440.0.0-alpine` base image we also get updated to Alpine 3.18.2 in the image which patches some security issues.
| Scenario | Provider | gcloud version | K8s Version      | Kubeconfig  | Orchestration | Order  | Cadence        |
|----------|----------|----------------|------------------|-------------|---------------|--------|----------------|
| 1        | GCP      | 440.0.0        | v1.26.5-gke.2700 | static      | DO            | * | fast:2020      |
| 2        | GCP      | 440.0.0        | v1.26.5-gke.2700 | auth plugin | DO            | * | stable:2023.07 |
> feat: (IAC-1097) Update Google Cloud CLI to 440.0.0

- files/cloud-init/jump/cloud-config
When a new jump server vm is created, it sets file ownership and permissions for the mounted NFS location which allows Viya services to initialize successfully. Importantly, the file system settings should only be applied once and not repeatedly in the event that the jump vm is destroyed and recreated in the same cluster. This change checks if the `${jump_rwx_filestore_path}/pvs` folder already exists and skips creating the folder and recursively setting ownerships and permissions if it does. If the jump vm is being created for the first time when the pvs folder is absent, creating the folder and setting permissions and ownership will occur an initial time and not thereafter.
Executed the following workflow to verify that file permissions and ownership was not modified on Jump VM …
> fix: (IAC-1091) Prevent Jump VM cloud-init from overwriting existing file permissions/ownership

- docs/CONFIG-VARS.md
- variables.tf
Increases the default IP range for `database_subnet_cidr` from  `192.168.4.0/24` to  `192.168.4.0/23`. This is to mitigate an issue that some users were experiencing when provisioning 2+ Cloud SQL instances as part of the GCP IAC process, In some cases users would see an error that looks like: `Failed to create subnetwork. Couldn't find free blocks in allocated IP ranges. Please allocate new ranges for this service provider`. The recommendation from a Google support ticket was to increase the size of `database_subnet_cidr`. 
GCP: Private IP Documentation: https://cloud.google.com/sql/docs/mysql/private-ip#allocated_range_size
| Scenario | Provider | Cloud SQL Instances | K8s Version     | Order  | Cadence   | Notes …
> feat: (IAC-1022) Increase the Default IP Range for database_subnet_cidr

- .github/workflows/linter-analysis.yaml
Update the branch selector for the GitHub workflow to allow it to additionally run against branches that use the [path pattern](https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#about-branch-and-tag-names) (e.g. "fix/IAC-111").
The name of the source branch of this PR uses the path pattern `chore/IAC-1195` and the GitHub workflow was automatically run.
> chore: (IAC-1195) Update Branch Selector for GitHub Workflow

- main.tf
Update the code to resolve `terraform_deprecated_lookup` linting issues 
doc: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_lookup.md
Created infrastructure and ensured the `sas-iac-buildinfo` was present
```
$ kubectl get cm -n kube-system sas-iac-buildinfo -o yaml
apiVersion: v1
data:
git-hash: 1fc00df6e7bc14d261f71fa475e1cc887533adfe
iac-tooling: terraform
terraform: |
version: "1.6.3"
revision: null
provider-selections: {"registry.terraform.io/hashicorp/external":"2.3.1","registry.terraform.io/hashicorp/google":"4.63.1","registry.terraform.io/hashicorp/google-beta":"4.63.1","registry.terraform.io/hashicorp/kubernetes":"2.20.0","registry.terraform.io/hashicorp/local":"2.4.0","registry.terraform.io/hashicorp/null":"3.2.1","regis …
```
> chore: (IAC-1230) Resolve Linting Warning

- Dockerfile
- README.md
- main.tf
- modules/google_vm/main.tf
- network.tf
- variables.tf
- versions.tf
Updates 3rd party dependencies in this project to resolve security findings from our scanning tool. Consumers of the Dockerfile will automatically have these updated dependencies installed, and users who directly run this project on this host will need to update the dependencies themselves. A note in the release notes will be made about this.
Here is a summary of version updates as well as code changes that needed to be made as result of the update.
* Terraform 1.4.5 -> 1.7.0
* gcloud CLI 440.0.0 -> 460.0.0
* Versions:
* Initial Version: 4.63.1
* Final Version: 5.12.0
* Notes:
* Required as of `hashicorp/google` `v5.12.0` when using `google_service_networking_connection` in conjunction with CloudSQL instances in order to cleanly delete resources we need to set `deletion_policy = …
> feat: (IAC-1312) Update Dependencies to Resolve Security Warnings

- docs/CONFIG-VARS.md
- variables.tf
Update the default postgres `server_version` to 15
| Scenario | Provider | kubernetes_version   | server_version | Final Postgres Version | order  | cadence   |
|----------|----------|----------------------|----------------|------------------------|--------|-----------|
| 1        | GCP      | v1.27.10-gke.1152000 | 15             | POSTGRES_15_4          | ****** | fast:2020 |
> feat: (IAC-1348) Update the default Postgres server version to 15

- Dockerfile
- README.md
Updated the gcloud version to 471.0.0 to resolve security vulnerabilities 
| Scenario | Provider | kubernetes_version  | Order  | Cadence   | Notes |
|----------|----------|---------------------|--------|-----------|-------|
| 1        | GCP      | v1.28.8-gke.1095000 | * | fast:2020 | OOTB  |
> feat: (IAC-1402) Update Dependencies to Resolve Security Warnings

- Dockerfile
- README.md
Updated the gcloud version to 472.0.0 to resolve security vulnerabilities 
| Scenario | Provider | kubernetes_version  | Order  | Cadence   | Notes |
|----------|----------|---------------------|--------|-----------|-------|
| 1        | GCP      | v1.28.9-gke.1000000 | ****** | fast:2020 | OOTB  |
> feat: (IAC-1437) Update Dependencies to Resolve Security Warnings

- config/sample-input-tf-enterprise.tfvars
- docs/CONFIG-VARS.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- variables.tf
Updated examples, defaults, and docs to line up with sizing recommendations.
| Scenario | Provider | Example File                 | kubernetes_version   | Order  | Cadence   |
|----------|----------|------------------------------|----------------------|--------|-----------|
| 1        | GCP      | sample-input.tfvars          | v1.28.10-gke.1058000 | ****** | fast:2020 |
| 2        | GCP      | sample-input-connect.tfvars  | v1.28.10-gke.1058000 |        |           |
| 3        | GCP      | sample-input-defaults.tfvars | v1.29.5-gke.1060000  |        |           |
| 4        | GCP      | sample-input-ha.tfvars       | v1.28.10-gke.1058000 |        |           |
| 5        | GCP      | sample-input-minimal.tfvars  | v1.28.10-gke.1058000 |        |           |
| 6        | GCP      | …
> feat: (IAC-1025) Update IAC Sample Sizing

- Dockerfile
- README.md
- main.tf
- modules/google_vm/main.tf
- network.tf
- versions.tf
This is a breaking change and will be noted as so in the release notes.
To resolve security warnings we needed to bump up the version of the providers which in turn required us to bump up the minimum required terraform versions.
This transition to this new version should be smooth. Users who run this project directly on their host will need to update the terraform binary and update the providers and modules. Users of the Docker container can build and use the latest release. Users will not be able to manage their infrastructure using an older version of this project once they migrate to this version or initially start with it. More details to come in official release notes. 
Update binaries & Terraform providers/modules to resolve security warnings
* Terraform 1.7.3-> 1.8.5 (project min …
> feat!: (IAC-1474) Update binaries & Terraform providers/modules

- README.md
- docs/CONFIG-VARS.md
- docs/user/DockerUsage.md
- docs/user/KubernetesVersions.md
- docs/user/Locations.md
- docs/user/TerraformGCPAuthentication.md
- docs/user/TerraformUsage.md
Google naming conventions have changed. Google Cloud Platform is now called Google Cloud. This PR makes the required updates to adhere the new naming convention wherever applicable.
See more details here: https://cloud.google.com/blog/topics/developers-practitioners/introducing-new-homepage-google-cloud
> docs: (PSKD-704) Update refs to GCP in Docs

- docs/CONFIG-VARS.md
- variables.tf
Eliminate racially-insensitive terminology:
- varaibles:tf: replace internal uses of 'master' in strings
- CONFIG-VARS.md: replace internal uses of 'master' in strings
> fix: (PSKD-969) eliminate racially-insensitive terminology

- Dockerfile
- README.md
- config/sample-input-tf-enterprise.tfvars
- docs/CONFIG-VARS.md
- docs/user/TerraformGCPAuthentication.md
- examples/sample-input-byo.tfvars
- examples/sample-input-connect.tfvars
- examples/sample-input-ha.tfvars
- examples/sample-input-minimal.tfvars
- examples/sample-input.tfvars
- linting-configs/.tflint.hcl
- locals.tf
- main.tf
- modules/google_netapp/main.tf
- modules/google_netapp/outputs.tf
- modules/google_netapp/variables.tf
- modules/google_vm/main.tf
- network.tf
- outputs.tf
- variables.tf
- versions.tf
- vms.tf
* #223
* #224
* #225
* #228 
* #229
> 7.2.0 - January 16, 2025

- docs/CONFIG-VARS.md
- Update the example postgres servers database_flags value to fix the invalid syntax and include two working example name/value pairs that can be used to set database_flags correctly.
- After duplicating the error message noted in the internal ticket with the existing documentation format for database_flags, I updated the database_flags value for the default postgres server instance to use the format below that includes commas between name/value pairs and between each database_flags entry as required.
```
postgres_servers = {    
default = {    
database_flags         = [{ name = "cloudsql.enable_pg_cron", value = "true"}, { name = "cloudsql.enable_pgaudit", value = "true"}] 
},    
}     
```
- I checked the created postgres server instance in the GCP console to verify that both the …
> docs: Correct database_flags syntax for Postgres servers (PSKD-1437)

- docs/CONFIG-VARS.md
- examples/sample-input.tfvars
- main.tf
- variables.tf
**Summary**
- Refined Terraform logic for PostgreSQL provisioning to enforce version-specific validation and eliminate silent defaults.
**What Changed:**
- Strict validation added in variables.tf to ensure invalid combinations of server_version, edition, and machine_type fail fast with clear error messages.
- Removed silent defaulting behavior — values are no longer auto-corrected; misconfigurations are now surfaced to the user.
- Defaults are applied only when values are not explicitly set:
Default: PostgreSQL 15 + ENTERPRISE + db-custom-4-16384
- Enforced version rules:
PostgreSQL 16+ → requires ENTERPRISE_PLUS and db-perf-optimized-*
PostgreSQL <16 → requires ENTERPRISE and db-custom-*
- Updated documentation in CONFIG-VARS.md to reflect these changes.
| Test # | `server_version` …
> feat(postgres): support edition param for PG 16+ with defaults

- modules/google_vm/variables.tf
- vms.tf
Reverts sassoftware/viya4-iac-gcp#278
There is potential for data loss if a `terraform apply` is run against an existing 20.04 NFS server. Reverting this until we have have a better workaround.
> revert: "fix: update vm image to use Ubuntu 24.04 (PSKD-1841)"

- .github/release-drafter.yml
- .github/workflows/conventional-commits.yml
- modules/google_vm/main.tf
- modules/google_vm/variables.tf
- test/helpers/helper_test.go
- vms.tf
Follow up to #278 and #279. This updates the VM image used for the NFS server and Jump VM to Ubuntu 24.04 LTS. The old 20.04 image is EOL and no longer accessible.
This change respects any existing VM and will not delete/recreate it.
I've also updated the associated test file and added the `revert` conventional commit to the workflow.
> fix: update VMs to use Ubuntu 24.04

- examples/sample-input-singlestore.tfvars
- outputs.tf
- Added example .tfvars configuration for SingleStore deployment.
- Provided a ready-to-use configuration template to simplify setup.
- Updated output.tf to include storage_type_backend and netapp_volume_path variables for flexibility.
> feat: add support for singlestore on gcp and terraform output variables. (PSCLOUD-92, PSCLOUD-161)
